#pragma kernel CSMain

float MinValue;
float MaxValue;
float OpacityMultiplier;
RWTexture2D<float4> Tex;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 colour = Tex[id.xy];
    float value = (colour.r + colour.g + colour.b) * 0.3333f;

    if(value >= MinValue && value <= MaxValue)
    {
        return;
        Tex[id.xy] = float4(value,value,value,1);
    }

    Tex[id.xy]= float4(colour.rgb, OpacityMultiplier*MinValue);
}
